server.port=8034
eureka.client.enabled=false

spring.application.name=pharmacy
spring.datasource.url=jdbc:mysql://localhost:3306/pharmacy_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=BkN2XFq6Oo9Yl6DSm7Or3eVmDCC4Q03KpxluOAdZakI=